services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/go/src/image-functions
      - ~/.aws:/root/.aws # Use to deploy the lambda function by serverless
      - ./data/.npm:/.npm  # NPM cache
    user: "1000:1000"
    ports:
      - "3001:8080"
    env_file: 
      - .env
    command: bash -c "npm --prefix /go/src/image-functions/.node run watch"

  aws:
    image: luofuxiang/local-s3:native-1.12.2
    environment:
      - LOCAL_S3_LOGGING_LEVEL=WARN
      - MODE=PERSISTENCE
    env_file:
      - .env
    ports:
      - "4566:80"
    volumes:
      - localstack-data:/data

  gcs:
    image: fsouza/fake-gcs-server:latest
    ports:
      - "4443:4443"
    command: -scheme http
    volumes:
      - local-gcs-data:/storage

volumes:
  localstack-data:
    name: localstack_data
    external: true
  local-gcs-data:
