version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - .:/go/src/image-functions
      - ~/.aws:/root/.aws # Use to deploy the lambda function by serverless
    ports:
      - 3001:8080
    env_file: 
      - ./.env
    command: bash -c "npm --prefix /go/src/image-functions/.node run watch"

  aws:
    image: localstack/localstack:latest
    environment:
      # For more services: https://github.com/localstack/localstack/blob/master/doc/feature_coverage.md
      - SERVICES=s3
      - DEFAULT_REGION=ap-east-1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - 4566:4566
    volumes:
      - localstack-data:/tmp/localstack

volumes:
  localstack-data:
    name: localstack_data
    external: true
