service: product-functions

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  stage: ${env:APP_STAGE, 'dev'}
  region: ${env:AWS_REGION, 'eu-central-1'}
  timeout: 6
  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true
  exclude:
    - ./**
  include:
    - ./bin/**

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0 # for docker container hosting

functions:
  - '${file(src/handlers.yml)}'
