name: "Build"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.x'
      - name: Install dependencies
        run: make install
      - name: Lint check
        uses: golangci/golangci-lint-action@v6
      - name: Build
        run: make build
      - name: Testing
        run: make test
      - name: Testing by Postman CLI
        env:
          AUTH_KEY_TEST: 'a_test_auth_key'
        run: |
          bin/main &
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          postman collection run doc/postman/api_collection.json --env-var "host=http://localhost:8080" --env-var "AUTH_KEY=a_test_auth_key" --env-var "AUTH_USER=test"
